[options]
profile = "debug"

[features]
debug-logging = true
vmm-debug-logging = false

[extra_paths]
paths = [
    "C:/Program Files/qemu",
    "C:/Program Files/Docker/Docker/resources/bin",
    "C:/Users/mario/.cargo/bin",
]
